<?= $this->doctype() ?>

<html>
    <head>
        <?= $this->headTitle('Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php

            $this->headMeta()
                ->setCharset('UTF-8')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');


            /* Le styles */
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('adminLTE/css/skins/skin-blue-light.min.css'))
                        ->prependStylesheet($this->basePath('adminLTE/css/AdminLTE.min.css'))
                        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css') #Ionicons
                        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css') #Font Awesome
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'));


            /* Scripts */
            $this->headScript()
                        ->prependFile($this->basePath('js/bootstrap.min.js'))
                        ->prependFile($this->basePath('js/jquery-3.1.1.min.js'))
                        ->appendFile(
                            'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
                            'text/javascript',
                            ['conditional' => 'lt IE 9']
                        )
                        ->appendFile(
                            'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
                            'text/javascript',
                            ['conditional' => 'lt IE 9']
                        );


    		echo $this->headMeta();
    		echo $this->headLink();
    		echo $this->headStyle();
    		echo $this->headScript();
		?>

    </head>
    <body class="skin-blue-light">
		<div class="wrapper">

		  <!-- Main Header -->
		  <header class="main-header">

		    <!-- Logo -->
		    <a href="/" class="logo">
		      <!-- logo for regular state and mobile devices -->
		      <span class="logo-lg"><b>Skeleton</b>Application</span>
		    </a>

		    <!-- Header Navbar -->
		    <nav class="navbar navbar-static-top" role="navigation">
		      <!-- Sidebar toggle button-->
		      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
		        <span class="sr-only">Toggle navigation</span>
		      </a>
		      <!-- Navbar Right Menu -->
		      <div class="navbar-custom-menu">
		        <ul class="nav navbar-nav">


		          <!-- User Account Menu -->
		          <li class="dropdown user user-menu">
		            <!-- Menu Toggle Button -->
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i></a>
		            <ul class="dropdown-menu">
		              <!-- Menu Body -->
		              <li >
		                  <a href="#"><i class="fa fa-user"></i> <span>Profile</span></a>
	                  </li>
	                  <li>
		                  <a href="#"><i class="fa fa-sign-out"></i> <span>Sign Out</span></a>
		              </li>
		            </ul>
		          </li>
		        </ul>
		      </div>
		    </nav>
		  </header>
		  <!-- Left side column. contains the logo and sidebar -->
		  <aside class="main-sidebar">

		    <!-- sidebar: style can be found in sidebar.less -->
		    <section class="sidebar">

		      <!-- Sidebar Menu -->
		      <ul class="sidebar-menu">
		        <li class="header">CATEGORY</li>
		        <!-- Optionally, you can add icons to the links -->
		        <li class="active"><a href="/skeleton-module"><i class="fa fa-code-fork"></i> <span>Skeleton Module</span></a></li>
		        <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
		        <li class="treeview">
		          <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
		            <span class="pull-right-container">
		              <i class="fa fa-angle-left pull-right"></i>
		            </span>
		          </a>
		          <ul class="treeview-menu">
		            <li><a href="#">Link in level 2</a></li>
		            <li><a href="#">Link in level 2</a></li>
		          </ul>
		        </li>
		      </ul>
		      <!-- /.sidebar-menu -->
		    </section>
		    <!-- /.sidebar -->
		  </aside>

		  <!-- Content Wrapper. Contains page content -->
		  <div class="content-wrapper">

		      <!-- Your Page Content Here -->
		      <?= $this->content ?>

		  </div>
		  <!-- /.content-wrapper -->

		</div>
		<!-- ./wrapper -->

		<!-- REQUIRED JS SCRIPTS -->

		<!-- Optionally, you can add Slimscroll and FastClick plugins.
		     Both of these plugins are recommended to enhance the
		     user experience. Slimscroll is required when using the
		     fixed layout. -->
		<!-- SlimScroll 1.3.0 -->
		<!-- <script src="plugins/slimScroll/jquery.slimscroll.min.js"></script> -->
		<!-- FastClick -->
		<!-- <script src="plugins/fastclick/fastclick.js"></script> -->

        <?php $this->inlineScript()->appendFile($this->basePath('adminLTE/js/app.min.js'));?>

        <?= $this->inlineScript(); ?>
    </body>
</html>
